### ISSUE TITLE
unable to see the smileys in Top 20 Emoji

### ISSUE THREAD

**Issue by rakeshr234** [PetengDedet/WhatsApp-Analyzer#1]
Hi PetengDedet,

Good work by you!!
after execution i dont see smileys in my command prompt. Is there anything else i have to take care ?

Please find the following output.

#Top 20 Emoji
-----------------
          char_count
emj_char
?                 50
?                 44
?                 16
?                 14
?                 13
?                  9
?                  4
?                  3
?                  2
?                  2
?                  1

**Comment by rakeshr234** [comment]
I am running it in Windows

**Comment by PetengDedet** [comment]
Hi @rakeshr234 
to the use of special character such as emoji is depends on terminal support.
As mentioned [here](https://github.com/Microsoft/WSL/issues/590) , emoji does not work on Windows command prompt.
Fortunately the support of tabbed and emoji [coming soon](https://wccftech.com/microsofts-tabbed-windows-terminal/)
Or you can try it on linux/mac.
