### ISSUE TITLE
Date and Time Format

### ISSUE THREAD

**Issue by Yash-Git-Hub** [PetengDedet/WhatsApp-Analyzer#10]
A lot of chats follow the date and time pattern of a 12 hours clock the code does not keep that in mind

**Comment by PetengDedet** [comment]
Hi, can you please provide some example of datetime format?

**Comment by PetengDedet** [comment]
Closed by #11 PR fix. 
Thanks @meesha7 

Feel free to reopen on another datetime related stuff
