### ISSUE TITLE
Omitted media

### ISSUE THREAD

**Issue by albertopasqualetto** [PetengDedet/WhatsApp-Analyzer#16]
When loading a chat file without media, in the .txt there is a placeholder string in place of the media.

For example this line is from italian:
`08/11/21, 00:29 - Alberto: <Media omessi>`

I think those placeholders should be added to each language specific stopwords list.
Otherways "media" and "omessi" will be most the present words
![image](https://user-images.githubusercontent.com/39854348/170328084-e22d8bb5-c1ef-43d6-ada6-d6a7677777c5.png)

**Comment by PetengDedet** [comment]
Nice catch

You can add or modify the pattern in pattern.py here: https://github.com/PetengDedet/WhatsApp-Analyzer/blob/master/patterns.py#L38

**Comment by albertopasqualetto** [comment]
Thanks! #17
