### ISSUE TITLE
This chat has no member & This chat does not contain any datetime

### ISSUE THREAD

**Issue by yafp** [PetengDedet/WhatsApp-Analyzer#3]
I get the following output

```
Extracting data. Please wait....
Generating dataframe...
Generating plot...
This chat has no member
This chat does not contain any datetime
...
```

I assume it has to do with the format of the timestamp which seems typical german. Example

`16.06.18, 22:16`

which represents:

`DD.MM.YY, HH:MM`

Any chance you can add support for this kind of timestamp?

**Comment by PetengDedet** [comment]
Hi, this date format are not included yet in current version. I have a plan to support more timestamp format. If you have more timesstamp format, you can tell me so i can include it in next patch.
Thanks

**Comment by yafp** [comment]
well the format above is the one used on my german localized android device & its whatsapp logs. 

In case i stumble upon other formats later i'll let you know.
