### ISSUE TITLE
Ignore chatlines with no-media references

### ISSUE THREAD

**Issue by yafp** [PetengDedet/WhatsApp-Analyzer#4]
I did export my chat log with the option "without media"

This results in the exported .txt in some lines like that

`TIMESTAMP - MEMBER: <Medien ausgeschlossen>`

I assume those lines should be ignored in the data-collection, but right now they are included (i.e. in the wordlist)

**Comment by PetengDedet** [comment]
Hi, looks like it's Android version in German language. Since i not fluent in any language on the planet, i just put Indonesian and English.
If you like to add German version pattern, please tell me belows attachment pattern in german:
```
<Media omitted>
Message not supported
.vcf (file attached)
image omitted
video omitted
document omitted
Contact card omitted
audio omitted
GIF omitted
sticker omitted
```

Thanks ☕️

**Comment by yafp** [comment]
Hey,

is that something i can look up (documented format somewhere) or do you just need a best guessed translation?

**Comment by PetengDedet** [comment]
There is no documentation about the pattern out there. The current pattern i've use is the result of my observe from some iOS and Android devices.

In Android, there is no difference between attachment.
But in iOS the pattern can identified wether is an Image, GIF, Video, Voice, Document, Sticker, Contact Card, or PDF

If you use Android, this media is the only thing you get:
```
<Media omitted>
```
