### ISSUE TITLE
emojis with diff skin tone not showing properly

### ISSUE THREAD

**Issue by pcuellar** [PetengDedet/WhatsApp-Analyzer#9]
Hello, 

Having trouble displaying emojis with non-default skin tones on results.
MacOS 10.15.5
Python 3.8.1

<img width="685" alt="02_emojis_usados" src="https://user-images.githubusercontent.com/20482146/84227469-87f36f80-aab2-11ea-80ea-1a5665e23b36.png">

**Comment by PetengDedet** [comment]
Hi,
According to [this](https://github.com/carpedm20/emoji/commit/eef79eac8fed78d5260323df6f07b532201ef97e) figure out that the `emoji` package used in this repository includes below character as independent emoji:
```python
    u':light_skin_tone:': u'\U0001F3FB',
    u':medium_light_skin_tone:': u'\U0001F3FC',
    u':medium_skin_tone:': u'\U0001F3FD',
    u':medium_dark_skin_tone:': u'\U0001F3FE',
    u':dark_skin_tone:': u'\U0001F3FF',
````
this is caused `non-default skin tone` emoji counted as 2 different emoji
```python
import emoji

strings = [
    u"This is non default skin tone: 🙌🏻 👌🏽",
    u"This is default skin tone: 🤝 😶"
]
for i in strings:
    print(emoji.emoji_count(i))
    print(emoji.emoji_lis(i))

"""
Output:

4
[{'location': 31, 'emoji': '🙌'}, {'location': 32, 'emoji': '🏻'}, {'location': 34, 'emoji': '👌'}, {'location': 35, 'emoji': '🏽'}]
2
[{'location': 27, 'emoji': '🤝'}, {'location': 29, 'emoji': '😶'}]
"""
```

I still working around to solve this. But if you need temporal solution, you can manually replace `extract_emojis()` function in chatline.py https://github.com/PetengDedet/WhatsApp-Analyzer/blob/cca04144723e30fe303459c0f941a51996d52526/chatline.py#L162-L169 

with below code:

```python
def extract_emojis(self, string=""):
    emj = []
    non_default_skin = {
        u'\U0001F3FB': u':light_skin_tone:',
        u'\U0001F3FC': u':medium_light_skin_tone:',
        u'\U0001F3FD': u':medium_skin_tone:',
        u'\U0001F3FE': u':medium_dark_skin_tone:',
        u'\U0001F3FF': u':dark_skin_tone:'
    }

    for c in string:
        if c in emoji.UNICODE_EMOJI and c not in non_default_skin:
            emj.append(c)
    return emj
```

**Comment by pcuellar** [comment]
Thanks, that fixed the skin tone problem. Do you have a sense why the 🥳emoji is still not rendering correctly? (see previous picture).

**Comment by PetengDedet** [comment]
> Thanks, that fixed the skin tone problem. Do you have a sense why the 🥳emoji is still not rendering correctly? (see previous picture).

the `:partying_face:` emoji works well on my terminal. I think the problem is on your terminal font settings.

**Comment by pcuellar** [comment]
You're absolutely right. Thanks for your help.
